# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7afe7b410e87b2d885fef716b79f945f614a87c4f080adca64223b3a8c2f37d8ef5611bf7b96b269a25848bb85ff80d5c709f1273fc83e5e36d686fec86e945

test:
  secret_key_base: 2b115b2cff09b569dc3f25933b25457bb050081287cb7dd280dc5e1b684a7a101428a8b02aca16e6aa7fd7593957766f821ea5c8cb0a307e785f8d01f7e9482f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
